[DISCO-2169] Delete CircleCI approval task for prod deployment (#250)
* chore: remove unhold-to-deploy-to-prod build step

* docs: update release process documentation

* docs: add clarification for CD Jenkins trigger

* chore: consolidate stage and prod Docker image publication

* fix: remove redundant dependency 'docker-image-build' from 'docker-image-publish' in CircleCI config

* docs: update release process

Co-authored-by: Raphael Pierzina <raphael@hackebrot.de>

* chore: add check-for-deployment step

* chore: add check for docker-image-publish-locust

* fix: spacing in CircleCI config

* fix: schema in docker-image-publish-locust

* docs: add activity diagram of CircleCI main-workflow

---------

Co-authored-by: Raphael Pierzina <raphael@hackebrot.de>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,7 +28,6 @@ workflows:
       - contract-tests:
           <<: *pr-filters
           requires:
-            - checks
             - docker-image-build
       - docs-build:
           <<: *pr-filters
@@ -53,7 +52,6 @@ workflows:
       - contract-tests:
           <<: *main-filters
           requires:
-            - checks
             - docker-image-build
       - docs-build:
           <<: *main-filters
@@ -61,37 +59,20 @@ workflows:
           <<: *main-filters
           requires:
             - docs-build
-      - docker-image-publish-stage:
+      - check-for-deployment:
           <<: *main-filters
           requires:
             - checks
-            - unit-tests
-            - integration-tests
             - test-coverage-check
             - contract-tests
-            - docker-image-build
-      - docker-image-publish-merino-locust:
+      - docker-image-publish-locust:
           <<: *main-filters
           requires:
-            - docker-image-publish-stage
-      # The following job will require manual approval in the CircleCI web application.
-      # Once provided, and when all the requirements are fullfilled (e.g. tests)
-      - unhold-to-deploy-to-prod:
-          <<: *main-filters
-          type: approval
-          requires:
-            - checks
-            - unit-tests
-            - integration-tests
-            - test-coverage-check
-            - contract-tests
-            - docker-image-build
-      # On approval of the `unhold-to-deploy-to-prod` job, any successive job that requires it
-      # will run. In this case, it's manually triggering deployment to production.
-      - docker-image-publish-prod:
+            - check-for-deployment
+      - docker-image-publish:
           <<: *main-filters
           requires:
-            - unhold-to-deploy-to-prod
+            - docker-image-publish-locust
 
 jobs:
   checks:
@@ -192,12 +173,19 @@ jobs:
           command: |
             sudo chown 1000:1000 tests/contract/kinto-attachments
             make run-contract-tests
-  docker-image-publish-stage:
+  check-for-deployment:
     docker:
       - image: cimg/base:2022.08
     steps:
       - checkout
       - skip-if-do-not-deploy
+  docker-image-publish:
+    # Pushing a new production Docker image to the Docker Hub registry triggers a
+    # webhook that starts the Jenkins deployment workflow
+    docker:
+      - image: cimg/base:2022.08
+    steps:
+      - checkout
       - attach_workspace:
           at: /tmp/workspace
       - setup_remote_docker
@@ -206,33 +194,48 @@ jobs:
           command: docker load -i /tmp/workspace/merinopy.tar.gz
       - dockerhub-login
       - run:
-          name: Push to Docker Hub # Load tests are triggered though [load test: (abort|warn)] label.
+          name: Push to Docker Hub
+          # The commit tag signals deployment and load test instructions to Jenkins by
+          # modifying the Docker image tag name. The convention looks as follows:
+          #^(?P<environment>stage|prod)(?:-(?P<task>\w+)-(?P<onfailure>warn|abort))?-(?P<commit>[a-z0-9]+)$
           command: |
             if [ "${CIRCLE_BRANCH}" == "main" ]; then
+              PROD_DOCKER_TAG="prod-${CIRCLE_SHA1}"
               if git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: warn\]'; then
                 echo "Load test requested. Slack warning will be output if test fails and deployment workflow for prod will proceed."
-                DOCKER_TAG="stage-loadtest-warn-${CIRCLE_SHA1}"
+                STAGE_DOCKER_TAG="stage-loadtest-warn-${CIRCLE_SHA1}"
               elif git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: abort\]'; then
                 echo "Load test requested. Deployment workflow for prod will abort if load test fails."
-                DOCKER_TAG="stage-loadtest-abort-${CIRCLE_SHA1}"
+                STAGE_DOCKER_TAG="stage-loadtest-abort-${CIRCLE_SHA1}"
               else
-                DOCKER_TAG="stage-${CIRCLE_SHA1}"
+                STAGE_DOCKER_TAG="stage-${CIRCLE_SHA1}"
               fi
             fi
 
             if [ -n "${DOCKER_TAG}" ]; then
-              echo ${DOCKERHUB_REPO}:${DOCKER_TAG}
-              docker tag app:build ${DOCKERHUB_REPO}:${DOCKER_TAG}
+              echo ${DOCKERHUB_REPO}:${STAGE_DOCKER_TAG} ${DOCKERHUB_REPO}:${PROD_DOCKER_TAG}
+              docker tag app:build ${DOCKERHUB_REPO}:${STAGE_DOCKER_TAG}
+              docker tag app:build ${DOCKERHUB_REPO}:${PROD_DOCKER_TAG}
+              docker tag app:build ${DOCKERHUB_REPO}:latest
               docker images
-              docker push "${DOCKERHUB_REPO}:${DOCKER_TAG}"
+              docker push "${DOCKERHUB_REPO}:${STAGE_DOCKER_TAG}"
+              docker push "${DOCKERHUB_REPO}:${PROD_DOCKER_TAG}"
+              docker push "${DOCKERHUB_REPO}:latest"
             else
               echo "Not pushing to dockerhub for tag=${CIRCLE_TAG} branch=${CIRCLE_BRANCH}"
             fi
-  docker-image-publish-merino-locust:
+  docker-image-publish-locust:
     docker:
       - image: cimg/base:2022.08
     steps:
       - checkout
+      - run:
+          name: Check for load test directive
+          command: | 
+            if ! git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: abort\|warn\]'; then
+              echo "Skipping remaining steps in this job: load test not required."
+              circleci-agent step halt
+            fi
       - setup_remote_docker:
           docker_layer_caching: true
       - run:
@@ -253,37 +256,6 @@ jobs:
               docker images
               docker push "${DOCKERHUB_MERINO_LOCUST_REPO}:${DOCKER_TAG}"
               docker push "${DOCKERHUB_MERINO_LOCUST_REPO}:latest"
-            else
-              echo "Not pushing to dockerhub for tag=${CIRCLE_TAG} branch=${CIRCLE_BRANCH}"
-            fi
-  docker-image-publish-prod:
-    docker:
-      - image: cimg/base:2022.08
-    steps:
-      - checkout
-      - skip-if-do-not-deploy
-      - attach_workspace:
-          at: /tmp/workspace
-      - setup_remote_docker
-      - run:
-          name: Load Docker image from workspace
-          command: docker load -i /tmp/workspace/merinopy.tar.gz
-      - dockerhub-login
-      - run:
-          name: Push to Docker Hub (prod)
-          # Using a different tag `prod-{CIRCLE_SHA1}` for production deployments
-          command: |
-            if [ "${CIRCLE_BRANCH}" == "main" ]; then
-              DOCKER_TAG="prod-${CIRCLE_SHA1}"
-            fi
-
-            if [ -n "${DOCKER_TAG}" ]; then
-              echo ${DOCKERHUB_REPO}:${DOCKER_TAG}
-              docker tag app:build ${DOCKERHUB_REPO}:${DOCKER_TAG}
-              docker tag app:build ${DOCKERHUB_REPO}:latest
-              docker images
-              docker push "${DOCKERHUB_REPO}:${DOCKER_TAG}"
-              docker push "${DOCKERHUB_REPO}:latest"
             else
               echo "Not pushing to dockerhub for tag=${CIRCLE_TAG} branch=${CIRCLE_BRANCH}"
             fi
