fix: schema in docker-image-publish-locust

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -230,12 +230,12 @@ jobs:
     steps:
       - checkout
       - run:
-        name: Check for load test tag
-        command: | 
-          if ! git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: abort\|warn\]'; then
-            echo "Skipping remaining steps in this job: load test not required."
-            circleci-agent step halt
-          fi
+          name: Check for load test directive
+          command: | 
+            if ! git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: abort\|warn\]'; then
+              echo "Skipping remaining steps in this job: load test not required."
+              circleci-agent step halt
+            fi
       - setup_remote_docker:
           docker_layer_caching: true
       - run:
