chore: add check for docker-image-publish-locust

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -65,14 +65,14 @@ workflows:
             - checks
             - test-coverage-check
             - contract-tests
-      - docker-image-publish-merino-locust:
+      - docker-image-publish-locust:
           <<: *main-filters
           requires:
             - check-for-deployment
       - docker-image-publish:
           <<: *main-filters
           requires:
-            - docker-image-publish-merino-locust
+            - docker-image-publish-locust
 
 jobs:
   checks:
@@ -224,11 +224,18 @@ jobs:
             else
               echo "Not pushing to dockerhub for tag=${CIRCLE_TAG} branch=${CIRCLE_BRANCH}"
             fi
-  docker-image-publish-merino-locust:
+  docker-image-publish-locust:
     docker:
       - image: cimg/base:2022.08
     steps:
       - checkout
+      - run:
+        name: Check for load test tag
+        command: | 
+          if ! git log -1 "$CIRCLE_SHA1" | grep -q '\[load test: abort\|warn\]'; then
+                echo "Skipping remaining steps in this job: load test not required."
+                circleci-agent step halt
+          fi
       - setup_remote_docker:
           docker_layer_caching: true
       - run:
